---
version: '3.7'

services:
#  backend-app:
#    build:
#      context: .
#    container_name: messenger-backed
#    command: [ "java", "org.springframework.boot.loader.JarLauncher" ]
#    image: messenger-backed:${TAG:-latest}
#    networks:
#      - messenger
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#       spring_profiles_active: dev
#       DATABASE_HOST: postgres
#       DATABASE_USER: postgres
#       DATABASE_PASSWORD: postgres
#       DATABASE_PORT: 5432

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12.8-alpine3.14
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "messenger"
    networks:
      - messenger
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

networks:
  messenger:
    name: messenger

volumes:
  postgres-data:
